version: '3'

services:
  szeyap-api:
    build:
      context: ./szeyap-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./szeyap-api:/usr/src/app
    command: ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "api:app", "--bind=0.0.0.0:8000"]
